[opener]
play = [
	{ run = 'xdg-open "$@"', desc = "Open" }
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = 'tilix -w "$@"', block = false, desc = "Open in Terminal" }
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
