[opener]
play = [
  { run = 'xdg-open "$@"', desc = "Open" }
]
edit = [
  { run = 'hx "$@"', desc = "Edit" },
  { run = 'tilix -w "$@"', block = false, desc = "Open in Terminal" }
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
