[opener]
play = [
	{ run = 'xdg-open "$@"', desc = "Open" }
]
edit = [
  { run = 'hx "$@"', block = true },
  { run = 'code "$@"', block = true }
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
